define(function (require,exports,module){
    return {
    	defaultData:{
    		38:[{
	    		'translateX':-209.53,
		    	'translateY':172.77,
		    	'translateZ':-362.92,
		    	'rotateX':0,
		    	'rotateY':-330,
		    	'rotateZ':0,
		    	'scaleX':100,
		    	'scaleY':100,
		    	'scaleZ':100
	    	},{
	    		'translateX':-209.53,
		    	'translateY':72,
		    	'translateZ':-362.92,
		    	'rotateX':0,
		    	'rotateY':-330,
		    	'rotateZ':0,
		    	'scaleX':100,
		    	'scaleY':100,
		    	'scaleZ':100
	    	}],
	    	car_TS:[{
	    		'translateX':-264,
		    	'translateY':213,
		    	'translateZ':362.92,
		    	'rotateX':0,
		    	'rotateY':-210,
		    	'rotateZ':0,
		    	'scaleX':100,
		    	'scaleY':100,
		    	'scaleZ':100
	    	},{
	    		'translateX':-264,
		    	'translateY':193,
		    	'translateZ':362.92,
		    	'rotateX':0,
		    	'rotateY':-210,
		    	'rotateZ':0,
		    	'scaleX':100,
		    	'scaleY':100,
		    	'scaleZ':100
	    	}],
	    	music_TS:[{
	    		'translateX':238.32,
		    	'translateY':370,
		    	'translateZ':296.32,
		    	'rotateX':0,
		    	'rotateY':-135,
		    	'rotateZ':0,
		    	'scaleX':100,
		    	'scaleY':100,
		    	'scaleZ':100
	    	},{
	    		'translateX':238.32,
		    	'translateY':340,
		    	'translateZ':296.32,
		    	'rotateX':0,
		    	'rotateY':-135,
		    	'rotateZ':0,
		    	'scaleX':100,
		    	'scaleY':100,
		    	'scaleZ':100
	    	}],
	    	touch_TS:[{
	    		'translateX':300.01,
		    	'translateY':2,
		    	'translateZ':-196.74,
		    	'rotateX':0,
		    	'rotateY':-62,
		    	'rotateZ':0,
		    	'scaleX':100,
		    	'scaleY':100,
		    	'scaleZ':100
	    	},{
	    		'translateX':300.01,
		    	'translateY':20,
		    	'translateZ':-196.74,
		    	'rotateX':0,
		    	'rotateY':-62,
		    	'rotateZ':0,
		    	'scaleX':100,
		    	'scaleY':100,
		    	'scaleZ':100
	    	}],
	    	video_TS:[{
	    		'translateX':-419.06,
		    	'translateY':-92.38,
		    	'translateZ':0,
		    	'rotateX':0,
		    	'rotateY':-270,
		    	'rotateZ':0,
		    	'scaleX':100,
		    	'scaleY':100,
		    	'scaleZ':100
	    	},{
	    		'translateX':-419.06,
		    	'translateY':-75,
		    	'translateZ':0,
		    	'rotateX':0,
		    	'rotateY':-270,
		    	'rotateZ':0,
		    	'scaleX':100,
		    	'scaleY':100,
		    	'scaleZ':100
	    	}]
    	},
    	dataClick:{
    	
    		config1:{
		    	el:'touch_phone.png',
		    	opacity1:'52.png',
		    	opacity2:'53.png',
		    	opacity3:'50.png',
		    	opacity4:'51.png',
		    	text1:'touch_TS.png',
		    	text2:'text1.png',
		    	scale1:{
		    		'translateX':343.27,
			    	'translateY':-36.52,
			    	'translateZ':-240.36,
			    	'rotateX':0,
			    	'rotateY':-55,
			    	'rotateZ' :0,
			    	scaleX:0,
			    	scaleY:0,
			    	scaleZ:0
		    	},
		    	scale2:{
		    		'translateX':193.27,
			    	'translateY':-124.52,
			    	'translateZ':-240.36,
			    	'rotateX':0,
			    	'rotateY':-55,
			    	'rotateZ' :0,
			    	scaleX:100,
			    	scaleY:100,
			    	scaleZ:100
		    	},
		    	audioPlay:'#music4'
		    }
    		,
    		config2:{
		    	el:'music_TS.png',
		    	opacity1:'41.png',
		    	opacity2:'42.png',
		    	opacity3:'48.png',
		    	opacity4:'49.png',
		    	text1:'music_TS.png',
		    	text2:'text2.png',
		    	scale1:{
		    		'translateX':27.1,
			    	'translateY':120.53,
			    	'translateZ':379.8,
			    	'rotateX':0,
			    	'rotateY':-155,
			    	'rotateZ' :0,
			    	scaleX:0,
			    	scaleY:0,
			    	scaleZ:0
		    	},
		    	scale2:{
		    		'translateX':27.1,
			    	'translateY':120.53,
			    	'translateZ':379.8,
			    	'rotateX':0,
			    	'rotateY':-155,
			    	'rotateZ' :0,
			    	scaleX:100,
			    	scaleY:100,
			    	scaleZ:100
		    	},
		    	audioPlay:'#music2',
		    	note:'music.png'
		    }
    		,
    		config3:{
		    	el:'car_TS.png',
		    	opacity1:'30.png',
		    	opacity2:'47.png',
		    	opacity3:'43.png',
		    	opacity4:'44.png',
		    	text1:'car_TS.png',
		    	text2:'text3.png',
		    	scale1:{
		    		'translateX':-327.27,
			    	'translateY':-187,
			    	'translateZ':379.8,
			    	'rotateX':0,
			    	'rotateY':-205,
			    	'rotateZ' :0,
			    	scaleX:0,
			    	scaleY:0,
			    	scaleZ:0
		    	},
		    	scale2:{
		    		'translateX':-327.27,
			    	'translateY':-187,
			    	'translateZ':379.8,
			    	'rotateX':0,
			    	'rotateY':-205,
			    	'rotateZ' :0,
			    	scaleX:100,
			    	scaleY:100,
			    	scaleZ:100
		    	},
		    	audioPlay:'#music3'
		    },
    		config4:{
		    	el:'video.png',
		    	opacity1:'45.png',
		    	opacity2:'46.png',
		    	opacity3:'55.png',
		    	opacity4:'56.png',
		    	text1:'video_TS.png',
		    	text2:'text4.png',
		    	scale1:{
		    		'translateX':-544,
			    	'translateY':-160,
			    	'translateZ':-143.33,
			    	'rotateX':0,
			    	'rotateY':-290,
			    	'rotateZ' :0,
			    	scaleX:0,
			    	scaleY:0,
			    	scaleZ:0
		    	},
		    	scale2:{
		    		'translateX':-544,
			    	'translateY':-160,
			    	'translateZ':-143.33,
			    	'rotateX':0,
			    	'rotateY':-290,
			    	'rotateZ' :0,
			    	scaleX:100,
			    	scaleY:100,
			    	scaleZ:100
		    	},
		    	audioPlay:'#music5'
		    }
    	}
    }
});